import { name } from '../../package.json'

export function generateTypedefCode(env: Record<string, string>) {
  const envProps = Object.keys(env).map((key) => `  readonly ${key}: string`)

  const codes = [
    `/// <reference types="vite/client" />`,
    `// This file is auto-generated by ${name}, please do not edit it directly.`,
    `// @ts-nocheck`,
    ``,
    `interface ImportMeta {`,
    `  readonly env: ImportMetaEnv`,
    `}`,
    ``,
    `interface ImportMetaEnv {`,
    ...envProps,
    `}`,
  ]

  return codes.join('\n')
}
