/// <reference types="vite/client" />
// This file is auto-generated by @0x-jerry/unplugin-env, please do not edit it directly.
// @ts-nocheck

interface ImportMeta {
  readonly env: ImportMetaEnv
}

interface ImportMetaEnv {
  readonly TT_C: string
}